global with sharing class AditionalInput {
    public AditionalInput() {}
        @AuraEnabled 
        public String type;
        @AuraEnabled 
        public String aka;
        @AuraEnabled
        public String firstname;
        @AuraEnabled
        public String lastname;
        @AuraEnabled
        public Date birthdate;
        @AuraEnabled
        public String phone;
        @AuraEnabled
        public String email;
        @AuraEnabled
        public String cpf;
        @AuraEnabled
        public Boolean optin;
        @AuraEnabled
        public String zipcode;
        @AuraEnabled
        public String number_z;
        @AuraEnabled
        public String complement;

}