public with sharing class DefinedResponseGetCasesTDCA {
    
        @AuraEnabled
        public String caseNumber;
        @AuraEnabled
        public String orderNumber;
        @AuraEnabled
        public String modality;
        @AuraEnabled
        public String documentNumber;
        @AuraEnabled
        public String typeorder;
        @AuraEnabled
        public String category;
        @AuraEnabled
        public String reason;
        @AuraEnabled
        public String event;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String brand;
        @AuraEnabled
        public String protocolTypeName;
        @AuraEnabled
        public String dateCreation;
        @AuraEnabled
        public String type;
        @AuraEnabled
        public String url;
        @AuraEnabled
        public String channel;
        @AuraEnabled
        public Boolean isVoiceSlaOnTime;
        @AuraEnabled
        public String consigmentCode;
}