global class FlowResponseProtocolo {
        @AuraEnabled @InvocableVariable
        public Integer protocolo;
        @AuraEnabled @InvocableVariable
        public String status;
        @AuraEnabled @InvocableVariable
        public Datetime date_Z;
        @AuraEnabled @InvocableVariable
        public String dateUpdate;
        @AuraEnabled @InvocableVariable
        public Integer resolution;
        @AuraEnabled @InvocableVariable
        public String protocoloResolutionDate;
        @AuraEnabled @InvocableVariable
        public String expertFullName;
        @AuraEnabled @InvocableVariable
        public String categoryID;
        @AuraEnabled @InvocableVariable
        public String statusPrazo;
        @AuraEnabled @InvocableVariable
        public Integer workFlowStatus;
        @AuraEnabled @InvocableVariable
        public String dataVencimento;
        @AuraEnabled @InvocableVariable
        public String TagID;
        @AuraEnabled @InvocableVariable
        public String ProtocoloFieldA;
        @AuraEnabled @InvocableVariable 
        public String bodyProtocolo;
        @AuraEnabled @InvocableVariable
        public String tagNumbers;
}