public class IdentificarSocioTO {
	public class ResponseWrapper{
		public Integer uniqueid;
		public String firstname;
		public String cpf;
		public String lastname;
		public String renovationdate;
		public Integer favoritestore;
		public String store;
		public String status;
		public String aka;
		public String fullnumber;
		public String photo;
		public String birthdate;
		public String email;
		public String phone;
		public String cep;
		public String streetname;
		public String number_Z; // in json: number
		public String complement;
		public String neighbour;
		public String city;
		public String state;
		public Boolean autorenovation; 
		public Boolean trialpass;
		public Integer memberiD;
        public boolean plus;
	}
}