public with sharing class ResponseGetCustomerWrapper {
    @InvocableVariable
    public String name;
    @InvocableVariable
    public String email;
    @InvocableVariable
    public String document;
    @InvocableVariable
    public String birthDate;
    @InvocableVariable
    public String Phone;
    @InvocableVariable
    public String homePhone;
    @InvocableVariable
    public String businessPhone;
    @InvocableVariable
    public String updatedIn;
    @InvocableVariable
    public String brand;
    @InvocableVariable
    public String status;
}